name: "Sidecar Poetry Dependencies"
description: "A GitHub Action to install dependencies in a sidecar container"
author: "darkvus"
inputs:
  token:
    description: "GitHub token"
    required: true
  organization:
    description: "GitHub organization"
    required: true
  repository:
    description: "GitHub repository"
    required: true
  branch:
    description: "GitHub branch"
    default: "develop"
    required: false
  package:
    description: "Dependency to install"
    required: true
  extra_poetry_args:
    description: "Extra arguments to pass to poetry"
    required: false
  package_version:
    description: "Version of the dependency to install"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
