name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.24.3
        uses: actions/setup-go@v1
        with:
          go-version: 1.24.3

      - uses: actions/checkout@v4

      - name: Build
        run: |
          go get -d -v
          go build -v .
